### ISSUE TITLE
在Python2.7.14环境下运行报错

### ISSUE THREAD

**Issue by ShenKeeeew** [BennyThink/UDP53-Filter-Type#1]
![image](https://user-images.githubusercontent.com/16913027/32114178-4f814a52-bb75-11e7-8d3f-e8becacdc567.png)
异常的变量没了。。emmmm我这么描述对嘛

**Comment by BennyThink** [comment]
尽管没能重现，但还是给写成函数式并且支持Python 3，所以应该不会这样报错了。
