### ISSUE TITLE
Connected to network, but unable to connect to the server.

### ISSUE THREAD

**Issue by roaming-debug** [BennyThink/UDP53-Filter-Type#2]
`error: [Errno 61] Connection refused`
I am confused.

**Comment by BennyThink** [comment]
Okay, let me explain this to you.

If you see a `connection refuse` prompt, this means you have successfully connected to my server, and my server told you "go away".  In other words, you are good to go.


[Reference](https://github.com/BennyThink/UDP53-Filter-Type/blob/master/THEORY.MD)

**Comment by roaming-debug** [comment]
> Okay, let me explain this to you.
> 
> If you see a `connection refuse` prompt, this means you have successfully connected to my server, and my server told you "go away". In other words, you are good to go.
> 
> [Reference](https://github.com/BennyThink/UDP53-Filter-Type/blob/master/THEORY.MD)

But under the same network, my phone showed  111 error, so what's the difference between them.

**Comment by BennyThink** [comment]
This script only supports Windows, and probably py2. The error code seems to be different on different platforms. But you could try using bare socket
```python
import socket

HOST = 'shemissed.me'
PORT = 53
sock_clt = socket.socket(socket.AF_INET, socket.SOCK_STREAM)

sock_clt.connect((HOST, PORT))
sock_clt.send(b'Hi')
```

Explain: send tcp request to this server.

**Comment by roaming-debug** [comment]
Well, I clearly understand it is a tcp request, but if I changed the port to 52, the error still is 61, which can't tell if this socket ever contacted with your server. BTW, the error happened after running `s.connect((HOST, PORT))`

**Comment by BennyThink** [comment]
TCP port 52 is closed on my server. Connection refuse is the normal behaviour because my kernel drops it.(Telling you 'go away')

**Comment by roaming-debug** [comment]
The confusing point is that I got the same error code whether the port on your server is closed or telling me "go away"... So if your server could send some data back, it will remove user's confusion...

**Comment by BennyThink** [comment]
> port on your server is closed

My bad. That depends on firewall policies. For iptables, input chain drop will result in timeout, reject/allow will result in connection refused.

Your suggestion is another way to solve the problem. However, it's too complicate. A message of  connection refuse is enough. 

Check out what wireshark says:
An SYN with an ACK, that is enough, the communication is done, it's a process of send-and-receive.
![image](https://user-images.githubusercontent.com/14024832/71731571-11f23900-2e80-11ea-9f24-9b99b91794d2.png)

if server is down/input chain deny, it would keep TCP retransmission until timeout. You'll never see an ACK, you're always send the tcp requests.

![image](https://user-images.githubusercontent.com/14024832/71731740-78775700-2e80-11ea-94a5-36e7a7c49777.png)

**Comment by roaming-debug** [comment]
Confusion cleared. Appreciate your explanation 👍  :)
